#!/bin/bash

# Master User Creation Guide for Clerk
# This script provides instructions for creating the master user

echo "🔐 MASTER USER CREATION GUIDE"
echo "=============================="
echo ""
echo "Since we don't have the Clerk secret key, here are two options:"
echo ""

echo "📋 OPTION 1: Manual Creation via Clerk Dashboard (Recommended)"
echo "--------------------------------------------------------------"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Select your application: Plataforma Astral"
echo "3. Navigate to 'Users' section"
echo "4. Click 'Add user' or 'Invite user'"
echo "5. Fill in the details:"
echo "   - Email: agustin@astral.cl"
echo "   - Password: 59163476a"
echo "   - First Name: Agustin"
echo "   - Last Name: (leave empty)"
echo "6. After creating the user, click on the user to edit"
echo "7. Go to 'Metadata' section"
echo "8. Add to 'Public metadata':"
echo "   {"
echo "     \"role\": \"MASTER\""
echo "   }"
echo "9. Save the changes"
echo ""

echo "📋 OPTION 2: Using Clerk API (if you have the secret key)"
echo "--------------------------------------------------------"
echo "1. Get your Clerk secret key from the dashboard"
echo "2. Run this command:"
echo "   CLERK_SECRET_KEY=sk_live_... ./scripts/create-clerk-user-curl.sh"
echo ""

echo "🔄 What happens next:"
echo "---------------------"
echo "• The user will be automatically synced to Convex via webhooks"
echo "• You'll be able to login with:"
echo "  - Email: agustin@astral.cl"
echo "  - Password: 59163476a"
echo "  - Role: MASTER (full system access)"
echo ""

echo "✅ Verification:"
echo "----------------"
echo "After creating the user, you can verify it worked by:"
echo "1. Going to your application login page"
echo "2. Trying to login with the credentials above"
echo "3. You should be redirected to the master dashboard"
echo ""

echo "🎯 Master Role Benefits:"
echo "----------------------"
echo "• Complete system access"
echo "• Can switch between all roles for testing"
echo "• Access to all administrative functions"
echo "• Security center and audit logs"
echo "• User management capabilities"
echo ""

echo "📞 Need Help?"
echo "-------------"
echo "If you encounter any issues:"
echo "1. Check the Clerk dashboard for user creation status"
echo "2. Verify the role metadata is set to 'MASTER'"
echo "3. Wait a few minutes for webhook sync to complete"
echo "4. Check browser console for any authentication errors"
echo ""

echo "🚀 Ready to create your master user!"
echo "Choose Option 1 (Dashboard) or Option 2 (API) above."
